#![allow(dead_code)]
//! Manual copy script generator for aruaru-desktop / aruaru-ai.
//!
//! The desktop and web UI can run automatic checks, but some users still need a
//! plain copyable script for offline PCs, locked-down Windows machines, or
//! emergency recovery. This module generates those scripts from one safe plan.

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CopyScriptKind {
    WindowsPowerShell,
    Bash,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CopyMode {
    Backup,
    Deploy,
    Mirror,
}

impl CopyMode {
    fn as_label(&self) -> &'static str {
        match self {
            CopyMode::Backup => "backup",
            CopyMode::Deploy => "deploy",
            CopyMode::Mirror => "mirror",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CopyScriptRequest {
    pub source_root: String,
    pub destination_root: String,
    pub mode: CopyMode,
    pub include_generated_readme: bool,
    pub include_logs: bool,
    pub dry_run_by_default: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedCopyScript {
    pub file_name: String,
    pub body: String,
    pub usage: String,
    pub safety_notes: Vec<String>,
}

pub fn generate_copy_script(
    kind: CopyScriptKind,
    req: &CopyScriptRequest,
) -> GeneratedCopyScript {
    match kind {
        CopyScriptKind::WindowsPowerShell => generate_powershell_copy_script(req),
        CopyScriptKind::Bash => generate_bash_copy_script(req),
    }
}

fn generate_powershell_copy_script(req: &CopyScriptRequest) -> GeneratedCopyScript {
    let dry_run_default = if req.dry_run_by_default { "$true" } else { "$false" };
    let include_generated = if req.include_generated_readme { "$true" } else { "$false" };
    let include_logs = if req.include_logs { "$true" } else { "$false" };

    let mut body = String::new();
    body.push_str("# aruaru manual copy script\n");
    body.push_str("# Generated by aruaru-desktop / aruaru-ai.\n");
    body.push_str("# Default is safe dry-run unless aruaru-ai explicitly generated otherwise.\n");
    body.push_str("# PowerShell rule: param(...) must be the first executable statement in the script.\n\n");
    body.push_str("param(\n");
    body.push_str(&format!(
        "  [string]$SourceRoot = \"{}\",\n",
        escape_ps(&req.source_root)
    ));
    body.push_str(&format!(
        "  [string]$DestinationRoot = \"{}\",\n",
        escape_ps(&req.destination_root)
    ));
    body.push_str(&format!("  [object]$DryRun = {},\n", dry_run_default));
    body.push_str(&format!("  [object]$IncludeGeneratedReadme = {},\n", include_generated));
    body.push_str(&format!("  [object]$IncludeLogs = {}\n", include_logs));
    body.push_str(")\n\n");
    body.push_str("$ErrorActionPreference = \"Stop\"\n\n");
    body.push_str("function Convert-AruaruBool($Value, [bool]$DefaultValue, [string]$Name) {\n");
    body.push_str("  if ($null -eq $Value) { return $DefaultValue }\n");
    body.push_str("  if ($Value -is [bool]) { return [bool]$Value }\n");
    body.push_str("  if ($Value -is [int]) { return ([int]$Value -ne 0) }\n");
    body.push_str("  $text = ([string]$Value).Trim()\n");
    body.push_str("  if ($text.StartsWith('$')) { $text = $text.Substring(1) }\n");
    body.push_str("  switch ($text.ToLowerInvariant()) {\n");
    body.push_str("    'true' { return $true } '1' { return $true } 'yes' { return $true } 'y' { return $true } 'on' { return $true }\n");
    body.push_str("    'false' { return $false } '0' { return $false } 'no' { return $false } 'n' { return $false } 'off' { return $false }\n");
    body.push_str("    default { throw \"Invalid boolean value for ${Name}: '$Value'. Use true/false, `$true/`$false, 1/0, yes/no, or on/off.\" }\n");
    body.push_str("  }\n");
    body.push_str("}\n\n");
    body.push_str("$DryRunValue = Convert-AruaruBool $DryRun $true \"DryRun\"\n");
    body.push_str("$IncludeGeneratedReadmeValue = Convert-AruaruBool $IncludeGeneratedReadme $false \"IncludeGeneratedReadme\"\n");
    body.push_str("$IncludeLogsValue = Convert-AruaruBool $IncludeLogs $false \"IncludeLogs\"\n\n");
    body.push_str("function Step($name) { Write-Host \"\"; Write-Host \"== $name ==\" }\n");
    body.push_str("function Ensure-Dir($path) { if (!(Test-Path -LiteralPath $path)) { New-Item -ItemType Directory -Force -Path $path | Out-Null } }\n\n");
    body.push_str("Step \"copy plan\"\n");
    body.push_str("Write-Host \"Source:      $SourceRoot\"\n");
    body.push_str("Write-Host \"Destination: $DestinationRoot\"\n");
    body.push_str("Write-Host \"DryRun:      $DryRun\"\n\n");
    body.push_str("if (!(Test-Path $SourceRoot)) { throw \"SourceRoot does not exist\" }\n");
    body.push_str("Ensure-Dir $DestinationRoot\n\n");
    body.push_str("$excludeDirs = @(\".git\", \"target\", \"node_modules\", \"dist\", \"build\", \"tmp-web\")\n");
    body.push_str("$excludeFiles = @(\".env\", \"*.key\", \"*.pem\", \"*.pfx\", \"id_rsa\", \"id_ed25519\")\n");
    body.push_str("if (-not $IncludeGeneratedReadme) { $excludeFiles += @(\"README.rs\", \"README.html\") }\n");
    body.push_str("if (-not $IncludeLogs) { $excludeDirs += @(\".aruaru\"); $excludeFiles += @(\"*.log\") }\n\n");
    body.push_str("Step \"file scan\"\n");
    body.push_str("$files = Get-ChildItem -Path $SourceRoot -Recurse -File | Where-Object {\n");
    body.push_str("  $relative = $_.FullName.Substring((Resolve-Path $SourceRoot).Path.Length).TrimStart('\\','/')\n");
    body.push_str("  $parts = $relative -split '[\\\\/]'\n");
    body.push_str("  foreach ($d in $excludeDirs) { if ($parts -contains $d) { return $false } }\n");
    body.push_str("  foreach ($f in $excludeFiles) { if ($_.Name -like $f) { return $false } }\n");
    body.push_str("  return $true\n");
    body.push_str("}\n");
    body.push_str("Write-Host (\"Files to copy: \" + $files.Count)\n\n");
    body.push_str("Step \"copy\"\n");
    body.push_str("foreach ($file in $files) {\n");
    body.push_str("  $srcRootFull = (Resolve-Path $SourceRoot).Path\n");
    body.push_str("  $relative = $file.FullName.Substring($srcRootFull.Length).TrimStart('\\','/')\n");
    body.push_str("  $dest = Join-Path $DestinationRoot $relative\n");
    body.push_str("  $destDir = Split-Path -Parent $dest\n");
    body.push_str("  if ($DryRun) { Write-Host (\"DRY-RUN copy \" + $relative); continue }\n");
    body.push_str("  Ensure-Dir $destDir\n");
    body.push_str("  Copy-Item -LiteralPath $file.FullName -Destination $dest -Force\n");
    body.push_str("}\n\n");
    body.push_str("Step \"done\"\n");
    body.push_str("if ($DryRun) { Write-Host \"OK: manual copy dry-run passed\" } else { Write-Host \"OK: manual copy completed\" }\n");

    GeneratedCopyScript {
        file_name: "aruaru-manual-copy.ps1".to_string(),
        usage: "PowerShell dry-run: powershell -ExecutionPolicy Bypass -File .\\aruaru-manual-copy.ps1".to_string(),
        body,
        safety_notes: common_safety_notes(req.mode.as_label()),
    }
}

fn generate_bash_copy_script(req: &CopyScriptRequest) -> GeneratedCopyScript {
    let dry_run_default = if req.dry_run_by_default { "1" } else { "0" };
    let include_generated = if req.include_generated_readme { "1" } else { "0" };
    let include_logs = if req.include_logs { "1" } else { "0" };

    let mut body = String::new();
    body.push_str("#!/usr/bin/env bash\n");
    body.push_str("set -euo pipefail\n\n");
    body.push_str(&format!("SOURCE_ROOT=\"{}\"\n", escape_sh(&req.source_root)));
    body.push_str(&format!("DESTINATION_ROOT=\"{}\"\n", escape_sh(&req.destination_root)));
    body.push_str(&format!("DRY_RUN=\"${{DRY_RUN:-{}}}\"\n", dry_run_default));
    body.push_str(&format!("INCLUDE_GENERATED_README=\"${{INCLUDE_GENERATED_README:-{}}}\"\n", include_generated));
    body.push_str(&format!("INCLUDE_LOGS=\"${{INCLUDE_LOGS:-{}}}\"\n\n", include_logs));
    body.push_str("echo '== copy plan =='\n");
    body.push_str("echo \"Source:      $SOURCE_ROOT\"\n");
    body.push_str("echo \"Destination: $DESTINATION_ROOT\"\n");
    body.push_str("echo \"DryRun:      $DRY_RUN\"\n\n");
    body.push_str("test -d \"$SOURCE_ROOT\"\nmkdir -p \"$DESTINATION_ROOT\"\n\n");
    body.push_str("EXCLUDES=(--exclude='.git' --exclude='target' --exclude='node_modules' --exclude='dist' --exclude='build' --exclude='tmp-web' --exclude='.env' --exclude='*.key' --exclude='*.pem' --exclude='*.pfx' --exclude='id_rsa' --exclude='id_ed25519')\n");
    body.push_str("if [[ \"$INCLUDE_GENERATED_README\" != \"1\" ]]; then EXCLUDES+=(--exclude='README.rs' --exclude='README.html'); fi\n");
    body.push_str("if [[ \"$INCLUDE_LOGS\" != \"1\" ]]; then EXCLUDES+=(--exclude='.aruaru' --exclude='*.log'); fi\n\n");
    body.push_str("if command -v rsync >/dev/null 2>&1; then\n");
    body.push_str("  if [[ \"$DRY_RUN\" == \"1\" ]]; then rsync -av --dry-run \"${EXCLUDES[@]}\" \"$SOURCE_ROOT/\" \"$DESTINATION_ROOT/\"; else rsync -av \"${EXCLUDES[@]}\" \"$SOURCE_ROOT/\" \"$DESTINATION_ROOT/\"; fi\n");
    body.push_str("else\n");
    body.push_str("  echo 'rsync not found. Please install rsync or use the PowerShell script on Windows.'\n");
    body.push_str("  exit 1\n");
    body.push_str("fi\n\n");
    body.push_str("if [[ \"$DRY_RUN\" == \"1\" ]]; then echo 'OK: manual copy dry-run passed'; else echo 'OK: manual copy completed'; fi\n");

    GeneratedCopyScript {
        file_name: "aruaru-manual-copy.sh".to_string(),
        usage: "Bash dry-run: chmod +x ./aruaru-manual-copy.sh && ./aruaru-manual-copy.sh".to_string(),
        body,
        safety_notes: common_safety_notes(req.mode.as_label()),
    }
}

fn common_safety_notes(mode: &str) -> Vec<String> {
    vec![
        format!("Copy mode: {mode}. Run dry-run first."),
        "Secret files such as .env, keys, and SSH private keys are excluded by default.".to_string(),
        "Generated README.rs / README.html are excluded unless explicitly requested.".to_string(),
        "No file is deleted by the generated safe-copy script.".to_string(),
        "aruaru-ai should show the script and ask for user approval before execution.".to_string(),
    ]
}

fn escape_ps(value: &str) -> String {
    value.replace('`', "``").replace('"', "`\"")
}

fn escape_sh(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn powershell_copy_script_excludes_secrets() {
        let req = CopyScriptRequest {
            source_root: "F:\\aruaru\\src".to_string(),
            destination_root: "F:\\aruaru\\backup".to_string(),
            mode: CopyMode::Backup,
            include_generated_readme: false,
            include_logs: false,
            dry_run_by_default: true,
        };
        let script = generate_copy_script(CopyScriptKind::WindowsPowerShell, &req);
        assert!(script.body.contains(".env"));
        assert!(script.body.contains("README.rs"));
        assert!(script.body.contains("DRY-RUN"));
        assert!(script.body.contains("[object]$DryRun"));
        assert!(script.body.contains("Convert-AruaruBool"));
        let param_pos = script.body.find("param(").expect("param block exists");
        let error_action_pos = script.body.find("$ErrorActionPreference").expect("error action exists");
        assert!(param_pos < error_action_pos, "param must appear before executable statements");
        assert!(script.file_name.ends_with(".ps1"));
    }

    #[test]
    fn bash_copy_script_uses_rsync_and_dry_run() {
        let req = CopyScriptRequest {
            source_root: "/srv/aruaru/src".to_string(),
            destination_root: "/srv/aruaru/backup".to_string(),
            mode: CopyMode::Deploy,
            include_generated_readme: true,
            include_logs: true,
            dry_run_by_default: true,
        };
        let script = generate_copy_script(CopyScriptKind::Bash, &req);
        assert!(script.body.contains("rsync"));
        assert!(script.body.contains("--dry-run"));
        assert!(script.file_name.ends_with(".sh"));
    }
}
