//! TOP100 programming-language popularity knowledge base for aruaru-ai.
//!
//! The production job refreshes the ranking every day from allowlisted public
//! sources. This seed data is a safe offline baseline for tests and UI design.
//! It intentionally treats popularity as a signal, not as proof of technical
//! superiority.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TopLanguageRecommendation {
    TopDefault,
    RecommendedOrSituational,
    ResearchBeforeUse,
    NotRecommendedByDefault,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TopLanguageRecord {
    pub rank: u16,
    pub language: &'static str,
    pub composite_basis: &'static str,
    pub features: &'static str,
    pub merits: &'static str,
    pub demerits: &'static str,
    pub author_or_governance: &'static str,
    pub author_policy_or_claim: &'static str,
    pub aruaru_recommendation: TopLanguageRecommendation,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Top100LanguageReport {
    pub title: &'static str,
    pub update_schedule: &'static str,
    pub ranking_policy: &'static str,
    pub source_policy: Vec<&'static str>,
    pub records: Vec<TopLanguageRecord>,
}

pub fn build_top100_language_report() -> Top100LanguageReport {
    Top100LanguageReport {
        title: "aruaru-ai TOP100 programming language report",
        update_schedule: "Daily at 03:30 Asia/Tokyo; keep latest.json, daily history, and diff markdown.",
        ranking_policy: "Composite ranking. TIOBE, GitHub Octoverse, Stack Overflow, PYPL, official release activity, security signals, and aruaru owner policy are stored separately. Popularity never means best language.",
        source_policy: vec![
            "TIOBE: monthly popularity indicator, not best-language ranking.",
            "GitHub Octoverse: repository activity and ecosystem trend signal.",
            "Stack Overflow Developer Survey: usage, admired/dreaded, and developer sentiment signal.",
            "PYPL: search-interest signal.",
            "Official documentation: highest priority for language facts and author/governance claims.",
            "Aruaru owner policy: displayed separately from internet evidence.",
        ],
        records: vec![
        TopLanguageRecord {
            rank: 1,
            language: "Python",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Readable high-level language widely used for AI, data, automation, and education.",
            merits: "Excellent for AI glue code, scripts, prototypes, and learning.",
            demerits: "Runtime typing, dependency drift, and performance limits require quality gates.",
            author_or_governance: "Guido van Rossum",
            author_policy_or_claim: "readability and beginner-friendly productivity",
            aruaru_recommendation: TopLanguageRecommendation::RecommendedOrSituational,
        },
        TopLanguageRecord {
            rank: 2,
            language: "TypeScript",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Typed superset of JavaScript for maintainable browser and tooling code.",
            merits: "Strong default for aruaru frontend because types, GraphQL codegen, and strict mode improve handoff.",
            demerits: "Build tooling and type definitions must be controlled to avoid complexity.",
            author_or_governance: "Microsoft / Anders Hejlsberg team",
            author_policy_or_claim: "typed JavaScript at scale",
            aruaru_recommendation: TopLanguageRecommendation::TopDefault,
        },
        TopLanguageRecord {
            rank: 3,
            language: "JavaScript",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Ubiquitous web scripting language supported by browsers.",
            merits: "Runs everywhere on the web.",
            demerits: "For aruaru default, plain JavaScript is discouraged; prefer TypeScript.",
            author_or_governance: "Brendan Eich",
            author_policy_or_claim: "browser scripting and web ubiquity",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 4,
            language: "Java",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Java is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Java's ecosystem and team skill.",
            demerits: "Do not select Java only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "James Gosling / Sun Microsystems",
            author_policy_or_claim: "write once, run anywhere and enterprise portability",
            aruaru_recommendation: TopLanguageRecommendation::RecommendedOrSituational,
        },
        TopLanguageRecord {
            rank: 5,
            language: "C#",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "C# is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match C#'s ecosystem and team skill.",
            demerits: "Do not select C# only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Anders Hejlsberg / Microsoft",
            author_policy_or_claim: "modern managed language for .NET productivity",
            aruaru_recommendation: TopLanguageRecommendation::RecommendedOrSituational,
        },
        TopLanguageRecord {
            rank: 6,
            language: "C++",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "C++ is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match C++'s ecosystem and team skill.",
            demerits: "Do not select C++ only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Bjarne Stroustrup",
            author_policy_or_claim: "zero-overhead abstractions and direct hardware control",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 7,
            language: "C",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "C is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match C's ecosystem and team skill.",
            demerits: "Do not select C only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Dennis Ritchie",
            author_policy_or_claim: "small systems language close to hardware",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 8,
            language: "Go",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Go is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Go's ecosystem and team skill.",
            demerits: "Do not select Go only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Robert Griesemer, Rob Pike, Ken Thompson",
            author_policy_or_claim: "simplicity, fast builds, network services",
            aruaru_recommendation: TopLanguageRecommendation::RecommendedOrSituational,
        },
        TopLanguageRecord {
            rank: 9,
            language: "Rust",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Systems language focused on memory safety, reliability, and performance without a garbage collector.",
            merits: "Strong default for aruaru core because compile-time checks reduce runtime bug risk.",
            demerits: "Learning curve and compile errors can be hard for beginners.",
            author_or_governance: "Graydon Hoare / Rust project",
            author_policy_or_claim: "memory safety and fearless concurrency without GC",
            aruaru_recommendation: TopLanguageRecommendation::TopDefault,
        },
        TopLanguageRecord {
            rank: 10,
            language: "PHP",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "PHP is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match PHP's ecosystem and team skill.",
            demerits: "Do not select PHP only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Rasmus Lerdorf",
            author_policy_or_claim: "pragmatic server-side web scripting",
            aruaru_recommendation: TopLanguageRecommendation::RecommendedOrSituational,
        },
        TopLanguageRecord {
            rank: 11,
            language: "SQL",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "SQL is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match SQL's ecosystem and team skill.",
            demerits: "Do not select SQL only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Donald D. Chamberlin, Raymond F. Boyce / IBM",
            author_policy_or_claim: "declarative relational data access",
            aruaru_recommendation: TopLanguageRecommendation::RecommendedOrSituational,
        },
        TopLanguageRecord {
            rank: 12,
            language: "Swift",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Swift is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Swift's ecosystem and team skill.",
            demerits: "Do not select Swift only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Apple / Chris Lattner and team",
            author_policy_or_claim: "safe modern Apple-platform development",
            aruaru_recommendation: TopLanguageRecommendation::RecommendedOrSituational,
        },
        TopLanguageRecord {
            rank: 13,
            language: "Kotlin",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Kotlin is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Kotlin's ecosystem and team skill.",
            demerits: "Do not select Kotlin only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "JetBrains",
            author_policy_or_claim: "concise pragmatic JVM and Android development",
            aruaru_recommendation: TopLanguageRecommendation::RecommendedOrSituational,
        },
        TopLanguageRecord {
            rank: 14,
            language: "Ruby",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Expressive dynamic language created by Yukihiro Matsumoto, with strong Japanese documentation and Rails history.",
            merits: "Good for existing Ruby/Rails maintenance when the team already understands the codebase.",
            demerits: "Not recommended by default for new aruaru-ai projects because expressive dynamic style can make handoff difficult after the original developer leaves.",
            author_or_governance: "Yukihiro Matsumoto",
            author_policy_or_claim: "developer happiness and expressive code",
            aruaru_recommendation: TopLanguageRecommendation::NotRecommendedByDefault,
        },
        TopLanguageRecord {
            rank: 15,
            language: "R",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "R is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match R's ecosystem and team skill.",
            demerits: "Do not select R only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Ross Ihaka, Robert Gentleman",
            author_policy_or_claim: "statistical computing and graphics",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 16,
            language: "Dart",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Dart is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Dart's ecosystem and team skill.",
            demerits: "Do not select Dart only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Google",
            author_policy_or_claim: "structured client apps and Flutter UI",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 17,
            language: "Scala",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Scala is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Scala's ecosystem and team skill.",
            demerits: "Do not select Scala only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Martin Odersky",
            author_policy_or_claim: "object-functional programming on the JVM",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 18,
            language: "Objective-C",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Objective-C is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Objective-C's ecosystem and team skill.",
            demerits: "Do not select Objective-C only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Brad Cox, Tom Love",
            author_policy_or_claim: "Smalltalk-style messaging on C for Apple legacy",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 19,
            language: "Visual Basic",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Visual Basic is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Visual Basic's ecosystem and team skill.",
            demerits: "Do not select Visual Basic only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Microsoft",
            author_policy_or_claim: "easy business application development",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 20,
            language: "MATLAB",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "MATLAB is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match MATLAB's ecosystem and team skill.",
            demerits: "Do not select MATLAB only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Cleve Moler / MathWorks",
            author_policy_or_claim: "matrix-first numerical computing",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 21,
            language: "Shell",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Shell is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Shell's ecosystem and team skill.",
            demerits: "Do not select Shell only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Unix shell lineage",
            author_policy_or_claim: "command composition and automation",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 22,
            language: "PowerShell",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "PowerShell is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match PowerShell's ecosystem and team skill.",
            demerits: "Do not select PowerShell only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Microsoft",
            author_policy_or_claim: "object-oriented automation for Windows and cloud",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 23,
            language: "Perl",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Perl is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Perl's ecosystem and team skill.",
            demerits: "Do not select Perl only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Larry Wall",
            author_policy_or_claim: "practical extraction/reporting and text processing",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 24,
            language: "Lua",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Lua is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Lua's ecosystem and team skill.",
            demerits: "Do not select Lua only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "PUC-Rio team",
            author_policy_or_claim: "small embeddable scripting",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 25,
            language: "Haskell",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Haskell is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Haskell's ecosystem and team skill.",
            demerits: "Do not select Haskell only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Haskell committee",
            author_policy_or_claim: "pure functional programming and strong types",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 26,
            language: "Elixir",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Elixir is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Elixir's ecosystem and team skill.",
            demerits: "Do not select Elixir only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Jose Valim",
            author_policy_or_claim: "concurrent fault-tolerant systems on BEAM",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 27,
            language: "Erlang",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Erlang is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Erlang's ecosystem and team skill.",
            demerits: "Do not select Erlang only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Joe Armstrong, Robert Virding, Mike Williams",
            author_policy_or_claim: "telecom-grade concurrency and fault tolerance",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 28,
            language: "F#",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "F# is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match F#'s ecosystem and team skill.",
            demerits: "Do not select F# only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Microsoft Research / Don Syme",
            author_policy_or_claim: "functional-first .NET",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 29,
            language: "Clojure",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Clojure is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Clojure's ecosystem and team skill.",
            demerits: "Do not select Clojure only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Rich Hickey",
            author_policy_or_claim: "simplicity, immutability, hosted Lisp",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 30,
            language: "Groovy",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Groovy is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Groovy's ecosystem and team skill.",
            demerits: "Do not select Groovy only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "James Strachan and community",
            author_policy_or_claim: "dynamic scripting on the JVM",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 31,
            language: "Julia",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Julia is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Julia's ecosystem and team skill.",
            demerits: "Do not select Julia only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Jeff Bezanson, Stefan Karpinski, Viral Shah, Alan Edelman",
            author_policy_or_claim: "high-level numerical computing with speed",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 32,
            language: "Zig",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Zig is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Zig's ecosystem and team skill.",
            demerits: "Do not select Zig only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Andrew Kelley",
            author_policy_or_claim: "simple explicit systems programming and C interop",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 33,
            language: "Ada",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Ada is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Ada's ecosystem and team skill.",
            demerits: "Do not select Ada only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Jean Ichbiah / DoD effort",
            author_policy_or_claim: "high-integrity systems and reliability",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 34,
            language: "Fortran",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Fortran is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Fortran's ecosystem and team skill.",
            demerits: "Do not select Fortran only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "John Backus / IBM",
            author_policy_or_claim: "scientific and numeric computing",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 35,
            language: "COBOL",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "COBOL is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match COBOL's ecosystem and team skill.",
            demerits: "Do not select COBOL only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "CODASYL / Grace Hopper influence",
            author_policy_or_claim: "business data processing",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 36,
            language: "Assembly",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Assembly is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Assembly's ecosystem and team skill.",
            demerits: "Do not select Assembly only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "hardware architecture communities",
            author_policy_or_claim: "absolute machine-level control",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 37,
            language: "Delphi/Object Pascal",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Delphi/Object Pascal is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Delphi/Object Pascal's ecosystem and team skill.",
            demerits: "Do not select Delphi/Object Pascal only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Anders Hejlsberg / Borland",
            author_policy_or_claim: "rapid native desktop development",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 38,
            language: "Pascal",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Pascal is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Pascal's ecosystem and team skill.",
            demerits: "Do not select Pascal only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Niklaus Wirth",
            author_policy_or_claim: "structured programming education",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 39,
            language: "Lisp",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Lisp is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Lisp's ecosystem and team skill.",
            demerits: "Do not select Lisp only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "John McCarthy",
            author_policy_or_claim: "symbolic computation and code-as-data",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 40,
            language: "Scheme",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Scheme is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Scheme's ecosystem and team skill.",
            demerits: "Do not select Scheme only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Guy L. Steele, Gerald Jay Sussman",
            author_policy_or_claim: "minimal Lisp and language research",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 41,
            language: "Prolog",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Prolog is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Prolog's ecosystem and team skill.",
            demerits: "Do not select Prolog only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Alain Colmerauer, Robert Kowalski",
            author_policy_or_claim: "logic programming and rules",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 42,
            language: "Smalltalk",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Smalltalk is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Smalltalk's ecosystem and team skill.",
            demerits: "Do not select Smalltalk only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Alan Kay, Dan Ingalls, Adele Goldberg team",
            author_policy_or_claim: "pure object-oriented live environment",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 43,
            language: "OCaml",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "OCaml is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match OCaml's ecosystem and team skill.",
            demerits: "Do not select OCaml only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "INRIA / Caml team",
            author_policy_or_claim: "practical ML-family functional programming",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 44,
            language: "ReasonML",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "ReasonML is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match ReasonML's ecosystem and team skill.",
            demerits: "Do not select ReasonML only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Meta / community",
            author_policy_or_claim: "OCaml semantics with JS-friendly syntax",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 45,
            language: "Crystal",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Crystal is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Crystal's ecosystem and team skill.",
            demerits: "Do not select Crystal only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Ary Borenszweig and community",
            author_policy_or_claim: "Ruby-like syntax with static typing",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 46,
            language: "Nim",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Nim is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Nim's ecosystem and team skill.",
            demerits: "Do not select Nim only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Andreas Rumpf",
            author_policy_or_claim: "efficient expressive systems scripting",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 47,
            language: "V",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "V is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match V's ecosystem and team skill.",
            demerits: "Do not select V only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "V language project",
            author_policy_or_claim: "simple compiled language and fast builds",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 48,
            language: "D",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "D is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match D's ecosystem and team skill.",
            demerits: "Do not select D only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Walter Bright",
            author_policy_or_claim: "systems programming with high-level features",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 49,
            language: "Tcl",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Tcl is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Tcl's ecosystem and team skill.",
            demerits: "Do not select Tcl only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "John Ousterhout",
            author_policy_or_claim: "embeddable command language",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 50,
            language: "Awk",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Awk is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Awk's ecosystem and team skill.",
            demerits: "Do not select Awk only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Aho, Weinberger, Kernighan",
            author_policy_or_claim: "text scanning and reports",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 51,
            language: "Sed",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Sed is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Sed's ecosystem and team skill.",
            demerits: "Do not select Sed only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Unix community",
            author_policy_or_claim: "stream text editing",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 52,
            language: "Bash",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Bash is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Bash's ecosystem and team skill.",
            demerits: "Do not select Bash only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Brian Fox / GNU",
            author_policy_or_claim: "Unix shell automation",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 53,
            language: "Fish",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Fish is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Fish's ecosystem and team skill.",
            demerits: "Do not select Fish only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "fish-shell community",
            author_policy_or_claim: "user-friendly command shell",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 54,
            language: "Haxe",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Haxe is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Haxe's ecosystem and team skill.",
            demerits: "Do not select Haxe only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Nicolas Cannasse",
            author_policy_or_claim: "cross-target language portability",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 55,
            language: "Elm",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Elm is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Elm's ecosystem and team skill.",
            demerits: "Do not select Elm only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Evan Czaplicki",
            author_policy_or_claim: "reliable frontend apps with no runtime exceptions",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 56,
            language: "PureScript",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "PureScript is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match PureScript's ecosystem and team skill.",
            demerits: "Do not select PureScript only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Phil Freeman / community",
            author_policy_or_claim: "strongly typed functional frontend language",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 57,
            language: "Gleam",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Gleam is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Gleam's ecosystem and team skill.",
            demerits: "Do not select Gleam only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Louis Pilfold",
            author_policy_or_claim: "friendly typed language on BEAM",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 58,
            language: "Forth",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Forth is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Forth's ecosystem and team skill.",
            demerits: "Do not select Forth only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Charles H. Moore",
            author_policy_or_claim: "stack-based extensible control",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 59,
            language: "APL",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "APL is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match APL's ecosystem and team skill.",
            demerits: "Do not select APL only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Kenneth E. Iverson",
            author_policy_or_claim: "array programming notation",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 60,
            language: "J",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "J is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match J's ecosystem and team skill.",
            demerits: "Do not select J only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Kenneth E. Iverson, Roger Hui",
            author_policy_or_claim: "ASCII array language",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 61,
            language: "K",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "K is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match K's ecosystem and team skill.",
            demerits: "Do not select K only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Arthur Whitney",
            author_policy_or_claim: "terse array programming for finance",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 62,
            language: "Q",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Q is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Q's ecosystem and team skill.",
            demerits: "Do not select Q only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Kx Systems",
            author_policy_or_claim: "time-series database language",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 63,
            language: "SAS",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "SAS is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match SAS's ecosystem and team skill.",
            demerits: "Do not select SAS only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "SAS Institute",
            author_policy_or_claim: "statistical business analytics",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 64,
            language: "Stata",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Stata is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Stata's ecosystem and team skill.",
            demerits: "Do not select Stata only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "StataCorp",
            author_policy_or_claim: "statistics and econometrics workflow",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 65,
            language: "SPSS Syntax",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "SPSS Syntax is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match SPSS Syntax's ecosystem and team skill.",
            demerits: "Do not select SPSS Syntax only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "IBM / SPSS lineage",
            author_policy_or_claim: "statistical package automation",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 66,
            language: "Solidity",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Solidity is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Solidity's ecosystem and team skill.",
            demerits: "Do not select Solidity only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Gavin Wood / Ethereum community",
            author_policy_or_claim: "smart contracts for EVM",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 67,
            language: "Vyper",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Vyper is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Vyper's ecosystem and team skill.",
            demerits: "Do not select Vyper only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Ethereum community",
            author_policy_or_claim: "Python-like safer smart contracts",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 68,
            language: "Move",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Move is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Move's ecosystem and team skill.",
            demerits: "Do not select Move only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Meta / Diem, Aptos/Sui communities",
            author_policy_or_claim: "resource-oriented smart contracts",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 69,
            language: "Racket",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Racket is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Racket's ecosystem and team skill.",
            demerits: "Do not select Racket only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "PLT team",
            author_policy_or_claim: "language-oriented programming",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 70,
            language: "Common Lisp",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Common Lisp is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Common Lisp's ecosystem and team skill.",
            demerits: "Do not select Common Lisp only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "ANSI Common Lisp community",
            author_policy_or_claim: "industrial Lisp flexibility",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 71,
            language: "Emacs Lisp",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Emacs Lisp is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Emacs Lisp's ecosystem and team skill.",
            demerits: "Do not select Emacs Lisp only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "GNU Emacs community",
            author_policy_or_claim: "editor customization and automation",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 72,
            language: "AutoHotkey",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "AutoHotkey is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match AutoHotkey's ecosystem and team skill.",
            demerits: "Do not select AutoHotkey only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Chris Mallett / community",
            author_policy_or_claim: "Windows macro automation",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 73,
            language: "AutoIt",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "AutoIt is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match AutoIt's ecosystem and team skill.",
            demerits: "Do not select AutoIt only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Jonathan Bennett / community",
            author_policy_or_claim: "Windows GUI automation",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 74,
            language: "LabVIEW",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "LabVIEW is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match LabVIEW's ecosystem and team skill.",
            demerits: "Do not select LabVIEW only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "National Instruments",
            author_policy_or_claim: "visual dataflow instrumentation",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 75,
            language: "Scratch",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Scratch is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Scratch's ecosystem and team skill.",
            demerits: "Do not select Scratch only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "MIT Lifelong Kindergarten",
            author_policy_or_claim: "beginner-friendly block programming",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 76,
            language: "Blockly",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Blockly is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Blockly's ecosystem and team skill.",
            demerits: "Do not select Blockly only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Google",
            author_policy_or_claim: "block programming toolkit",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 77,
            language: "Logo",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Logo is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Logo's ecosystem and team skill.",
            demerits: "Do not select Logo only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Wally Feurzeig, Seymour Papert, Cynthia Solomon",
            author_policy_or_claim: "learning through turtle graphics",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 78,
            language: "ABAP",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "ABAP is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match ABAP's ecosystem and team skill.",
            demerits: "Do not select ABAP only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "SAP",
            author_policy_or_claim: "SAP business application programming",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 79,
            language: "Apex",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Apex is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Apex's ecosystem and team skill.",
            demerits: "Do not select Apex only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Salesforce",
            author_policy_or_claim: "Salesforce platform business logic",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 80,
            language: "PL/SQL",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "PL/SQL is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match PL/SQL's ecosystem and team skill.",
            demerits: "Do not select PL/SQL only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Oracle",
            author_policy_or_claim: "procedural SQL in Oracle Database",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 81,
            language: "T-SQL",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "T-SQL is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match T-SQL's ecosystem and team skill.",
            demerits: "Do not select T-SQL only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Microsoft / Sybase lineage",
            author_policy_or_claim: "SQL Server procedural SQL",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 82,
            language: "PLpgSQL",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "PLpgSQL is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match PLpgSQL's ecosystem and team skill.",
            demerits: "Do not select PLpgSQL only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "PostgreSQL community",
            author_policy_or_claim: "PostgreSQL procedural SQL",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 83,
            language: "GraphQL SDL",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "GraphQL SDL is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match GraphQL SDL's ecosystem and team skill.",
            demerits: "Do not select GraphQL SDL only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Facebook / GraphQL Foundation",
            author_policy_or_claim: "typed API schema description",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 84,
            language: "HTML",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "HTML is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match HTML's ecosystem and team skill.",
            demerits: "Do not select HTML only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Tim Berners-Lee / W3C/WHATWG",
            author_policy_or_claim: "document structure for the web",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 85,
            language: "CSS",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "CSS is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match CSS's ecosystem and team skill.",
            demerits: "Do not select CSS only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Håkon Wium Lie / W3C",
            author_policy_or_claim: "separation of presentation and structure",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 86,
            language: "JSON",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "JSON is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match JSON's ecosystem and team skill.",
            demerits: "Do not select JSON only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Douglas Crockford / standards community",
            author_policy_or_claim: "simple data interchange",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 87,
            language: "YAML",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "YAML is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match YAML's ecosystem and team skill.",
            demerits: "Do not select YAML only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Clark Evans, Ingy döt Net, Oren Ben-Kiki",
            author_policy_or_claim: "human-readable configuration",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 88,
            language: "XML",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "XML is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match XML's ecosystem and team skill.",
            demerits: "Do not select XML only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "W3C",
            author_policy_or_claim: "structured extensible markup",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 89,
            language: "Markdown",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Markdown is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Markdown's ecosystem and team skill.",
            demerits: "Do not select Markdown only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "John Gruber, Aaron Swartz",
            author_policy_or_claim: "plain-text readable documentation",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 90,
            language: "LaTeX",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "LaTeX is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match LaTeX's ecosystem and team skill.",
            demerits: "Do not select LaTeX only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Leslie Lamport",
            author_policy_or_claim: "high-quality technical typesetting",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 91,
            language: "TeX",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "TeX is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match TeX's ecosystem and team skill.",
            demerits: "Do not select TeX only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Donald Knuth",
            author_policy_or_claim: "precise digital typesetting",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 92,
            language: "Verilog",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Verilog is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Verilog's ecosystem and team skill.",
            demerits: "Do not select Verilog only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Phil Moorby",
            author_policy_or_claim: "hardware description for digital circuits",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 93,
            language: "VHDL",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "VHDL is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match VHDL's ecosystem and team skill.",
            demerits: "Do not select VHDL only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "US DoD / IEEE",
            author_policy_or_claim: "strongly typed hardware description",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 94,
            language: "SystemVerilog",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "SystemVerilog is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match SystemVerilog's ecosystem and team skill.",
            demerits: "Do not select SystemVerilog only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Accellera / IEEE",
            author_policy_or_claim: "advanced hardware design and verification",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 95,
            language: "Chisel",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "Chisel is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match Chisel's ecosystem and team skill.",
            demerits: "Do not select Chisel only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "UC Berkeley",
            author_policy_or_claim: "hardware construction in Scala",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 96,
            language: "HDL Coder MATLAB",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "HDL Coder MATLAB is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match HDL Coder MATLAB's ecosystem and team skill.",
            demerits: "Do not select HDL Coder MATLAB only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "MathWorks",
            author_policy_or_claim: "model-based HDL generation",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 97,
            language: "CUDA C++",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "CUDA C++ is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match CUDA C++'s ecosystem and team skill.",
            demerits: "Do not select CUDA C++ only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "NVIDIA",
            author_policy_or_claim: "GPU parallel programming",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 98,
            language: "OpenCL C",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "OpenCL C is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match OpenCL C's ecosystem and team skill.",
            demerits: "Do not select OpenCL C only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "Khronos Group",
            author_policy_or_claim: "vendor-neutral heterogeneous compute",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 99,
            language: "WGSL",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "WGSL is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match WGSL's ecosystem and team skill.",
            demerits: "Do not select WGSL only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "W3C GPU for the Web community",
            author_policy_or_claim: "WebGPU shader programming",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        },
        TopLanguageRecord {
            rank: 100,
            language: "GLSL",
            composite_basis: "Composite TOP100 seed: TIOBE popularity, GitHub repository trends, Stack Overflow survey signals, PYPL/search interest, plus domain-specific adoption.",
            features: "GLSL is tracked as a TOP100 candidate from popularity indexes, repository trends, surveys, or domain-specific usage.",
            merits: "Useful when the project requirements match GLSL's ecosystem and team skill.",
            demerits: "Do not select GLSL only because it is popular; verify maintainability, security, hiring, and handoff risk.",
            author_or_governance: "OpenGL ARB / Khronos",
            author_policy_or_claim: "graphics shader programming",
            aruaru_recommendation: TopLanguageRecommendation::ResearchBeforeUse,
        }
        ],
    }
}

pub fn top100_language_markdown() -> String {
    let report = build_top100_language_report();
    let mut out = String::new();
    out.push_str("# aruaru-ai TOP100 Programming Languages\n\n");
    out.push_str(&format!("Update: {}\n\n", report.update_schedule));
    out.push_str(&format!("Policy: {}\n\n", report.ranking_policy));
    out.push_str("## Sources\n");
    for source in &report.source_policy {
        out.push_str(&format!("- {}\n", source));
    }
    out.push_str("\n## TOP100 records\n");
    for item in &report.records {
        out.push_str(&format!(
            "{}. {}\n   - Features: {}\n   - Merits: {}\n   - Demerits: {}\n   - Author / governance: {}\n   - Author policy / claim: {}\n   - aruaru recommendation: {:?}\n",
            item.rank,
            item.language,
            item.features,
            item.merits,
            item.demerits,
            item.author_or_governance,
            item.author_policy_or_claim,
            item.aruaru_recommendation
        ));
    }
    out
}

pub fn quality_gate_smoke_check() -> bool {
    let report = build_top100_language_report();
    let ruby = report.records.iter().find(|item| item.language == "Ruby");
    let rust = report.records.iter().find(|item| item.language == "Rust");
    let ts = report.records.iter().find(|item| item.language == "TypeScript");
    let markdown = top100_language_markdown();

    report.records.len() == 100
        && markdown.contains("Author policy / claim")
        && report.ranking_policy.contains("Popularity never means best")
        && ruby.is_some_and(|item| item.aruaru_recommendation == TopLanguageRecommendation::NotRecommendedByDefault)
        && rust.is_some_and(|item| item.aruaru_recommendation == TopLanguageRecommendation::TopDefault)
        && ts.is_some_and(|item| item.aruaru_recommendation == TopLanguageRecommendation::TopDefault)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn report_has_exactly_top100_records() {
        let report = build_top100_language_report();
        assert_eq!(report.records.len(), 100);
        assert_eq!(report.records.first().unwrap().rank, 1);
        assert_eq!(report.records.last().unwrap().rank, 100);
    }

    #[test]
    fn ruby_policy_is_visible_and_not_default() {
        let report = build_top100_language_report();
        let ruby = report.records.iter().find(|item| item.language == "Ruby").unwrap();
        assert_eq!(ruby.aruaru_recommendation, TopLanguageRecommendation::NotRecommendedByDefault);
        assert!(ruby.demerits.contains("handoff"));
        assert!(ruby.author_policy_or_claim.contains("developer happiness"));
    }

    #[test]
    fn report_separates_popularity_from_best_language() {
        let report = build_top100_language_report();
        assert!(report.ranking_policy.contains("Popularity never means best"));
        assert!(report.source_policy.iter().any(|item| item.contains("TIOBE")));
    }

    #[test]
    fn markdown_contains_author_policy() {
        let markdown = top100_language_markdown();
        assert!(markdown.contains("Author policy / claim"));
        assert!(markdown.contains("Ruby"));
        assert!(markdown.contains("TypeScript"));
    }
}
